// HABIT CONSTANTS

// Get all habits for a user
export const GET_HABITS_REQUEST = 'GET_HABITS_REQUEST';
export const GET_HABITS_SUCCESS = 'GET_HABITS_SUCCESS';
export const GET_HABITS_FAIL = 'GET_HABITS_FAIL';

// Create a new habit
export const CREATE_HABIT_REQUEST = 'CREATE_HABIT_REQUEST';
export const CREATE_HABIT_SUCCESS = 'CREATE_HABIT_SUCCESS';
export const CREATE_HABIT_FAIL = 'CREATE_HABIT_FAIL';
export const CREATE_HABIT_RESET = 'CREATE_HABIT_RESET';


// Get a single habit
export const GET_HABIT_DETAILS_REQUEST = 'GET_HABIT_DETAILS_REQUEST';
export const GET_HABIT_DETAILS_SUCCESS = 'GET_HABIT_DETAILS_SUCCESS';
export const GET_HABIT_DETAILS_FAIL = 'GET_HABIT_DETAILS_FAIL';

// Update a habit
export const UPDATE_HABIT_REQUEST = 'UPDATE_HABIT_REQUEST';
export const UPDATE_HABIT_SUCCESS = 'UPDATE_HABIT_SUCCESS';
export const UPDATE_HABIT_FAIL = 'UPDATE_HABIT_FAIL';
export const UPDATE_HABIT_RESET = 'UPDATE_HABIT_RESET';


// Delete a habit
export const DELETE_HABIT_REQUEST = 'DELETE_HABIT_REQUEST';
export const DELETE_HABIT_SUCCESS = 'DELETE_HABIT_SUCCESS';
export const DELETE_HABIT_FAIL = 'DELETE_HABIT_FAIL';
export const DELETE_HABIT_RESET = 'DELETE_HABIT_RESET';

// Mark habit as complete
export const MARK_HABIT_COMPLETE_REQUEST = 'MARK_HABIT_COMPLETE_REQUEST';
export const MARK_HABIT_COMPLETE_SUCCESS = 'MARK_HABIT_COMPLETE_SUCCESS';
export const MARK_HABIT_COMPLETE_FAIL = 'MARK_HABIT_COMPLETE_FAIL';
export const MARK_HABIT_COMPLETE_RESET = 'MARK_HABIT_COMPLETE_RESET';

// Get habit summary
export const GET_HABIT_SUMMARY_REQUEST = 'GET_HABIT_SUMMARY_REQUEST';
export const GET_HABIT_SUMMARY_SUCCESS = 'GET_HABIT_SUMMARY_SUCCESS';
export const GET_HABIT_SUMMARY_FAIL = 'GET_HABIT_SUMMARY_FAIL';


// Clear errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
